[traffic-cop]
primary = { ip = "localhost", port = "2888" }
secondary = { ip = "222.222.222.2", port = "2888" }

[cli]
primary = { ip = "localhost", port = "2234", logging = "trace" }

[api]
primary = { ip = "localhost", port = "2234", logging = "trace" }

[db]
primary = {db = "sled",  ip = "localhost", port = "2234", logging = "trace" }
secondary = {db = "sled",  ip = "localhost", port = "2234", logging = "trace" }

[logger]
primary = { ip = "localhost", port = "2234" }


