[traffic-cop]
primary = { ip = "localhost", port = "2888" }
secondary = { ip = "222.222.222.2", port = "2888" }

[cli]
primary = { ip = "localhost", port = "2234", logging = "trace" }
secondary = { ip = "localhost", port = "2235", logging = "trace" }

[api]
primary = { ip = "localhost", port = "2234", logging = "trace" }
secondary = { ip = "localhost", port = "2235", logging = "trace" }

[db]
primary = {db-type = "sled",  ip = "localhost", port = "2234", logging = "trace" }
secondary = {db-type = "sled",  ip = "localhost", port = "2334", logging = "trace" }

[logger]
local = { logger-type = "simple", directory = "/var/lib/vector" }
remote = { ip = "123.333.333.23", port = "2234" }


