[package]
name = "essembly-core"
version = "0.1.0"
authors = ["blittable <blittable-bits@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1.9"
tracing-subscriber = "0.1.4"
tracing-attributes = "0.1.4"
tracing-futures = "0.0.1-alpha.1"
tracing-log = "0.1.0"
ansi_term = "0.12.1"
humantime = "1.3"
log = "0.4"
chrono = "0.4.9"
mockall = "0.5.1"
uuid = { version = "0.7", features = ["serde", "v5"] }

[dev-dependencies]
mockall = "0.5.1"
