[package]
name = "essembly-api"
version = "0.1.0-alpha.1"
authors = ["blittable <blittable-bits@gmail.com>"]
edition = "2018"

[dependencies]
serde_derive = "1.0"
failure = "0.1.5"
lazy_static = "1.4.0"
http = "0.1"
tracing = "0.1"
tokio = { git = "https://github.com/tokio-rs/tokio.git" }
failure_derive = "=0.1.5"
tonic = { git = "https://github.com/hyperium/tonic", features = ["rustls"] }

futures-preview = { version = "=0.3.0-alpha.19", default-features = false, features = ["alloc"]}
tower = "0.3.0-alpha.2"

[dependencies.essembly]
path = "../essembly"
version = "0.1.0-alpha.1"
default-features = false 
features = ["logger"]


# The development profile, used for `cargo build`
[profile.dev]
opt-level = 3  
debug = true   




