[package]
name = "essembly-api"
version = "0.1.0-alpha.1"
authors = ["blittable <blittable-bits@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_json = "1.0"
fallible = "0.1.2"
serde_derive = "1.0"
serde_regex = "0.4.0"
tempfile = "3.0.0"
dirs = "2.0.2"
failure = "0.1.5"
lazy_static = "1.4.0"
http = "0.1"
tracing = "0.1"
tracing-core = { git = "https://github.com/tokio-rs/tracing", version = "0.1.7" }
tracing-log = { git = "https://github.com/tokio-rs/tracing", version = "0.1.1" }
tracing-subscriber = { git = "https://github.com/tokio-rs/tracing", version = "0.1.5" }
tracing-attributes = { git = "https://github.com/tokio-rs/tracing", version = "0.1.5" }
tracing-futures = { git = "https://github.com/tokio-rs/tracing", version = "0.1.1" }
tokio = { git = "https://github.com/tokio-rs/tokio.git" }
toml = "0.5"
failure_derive = "=0.1.5"
clap = {version = "2.33", features = ["yaml"]}
datetime = "0.4.7"
env_logger = "0.7.0"
num_cpus = "1.10.0"
scoped_threadpool = "0.1.9"
users = "0.9.1"
tonic = { git = "https://github.com/hyperium/tonic", features = ["rustls"] }
futures-preview = { version = "=0.3.0-alpha.19", default-features = false, features = ["alloc"]}
prost-derive = "0.5.0"
prost = "0.5"
bytes = "0.4"
tower = "0.3.0-alpha.2"
regex = "1.0"

essembly = { path = "../essembly", version = "0.1.0-alpha.1" }

# Tracing 
ansi_term = "0.12"
humantime = "1.3"
log = "0.4"

# The development profile, used for `cargo build`
[profile.dev]
opt-level = 3  
debug = true   




