[package]
name = "essembly"
version = "0.1.0-alpha.1"
authors = ["blittable <blittable-bits@gmail.com>"]
edition = "2018"
description = """
Secure, performant building blocks for applications
"""
categories = ["primitives", "business", "security", "encryption"]

[features]
default = [
"core",
"interfaces",
"cli",
"store",
]

core = ["essembly-core"]
interfaces = ["essembly-interfaces"]
cli = ["essembly-cli"]
store = ["essembly-store"]

[dependencies]
essembly-core = { version = "=0.1.0-alpha.1", optional = true, path = "../essembly-core" }
accounts = { version = "=0.1.0-alpha.1", optional = true, path = "../essembly-core/accounts" }
inventory = { version = "=0.1.0-alpha.1", optional = true, path = "../essembly-core/inventory" }

essembly-interfaces = { version = "=0.1.0-alpha.1", optional = true, path = "../essembly-interfaces" }

essembly-cli = { version = "=0.1.0-alpha.1", optional = true, path = "../essembly-cli" }
essembly-store = { version = "=0.1.0-alpha.1", optional = true, path = "../essembly-store" }
tracing = "0.1.9"
bitflags = "0.1.0"
tracing-subscriber = "0.1.4"
tracing-attributes = "0.1.4"
tracing-futures = "0.0.1-alpha.1"
ansi_term = "0.12.1"
humantime = "1.3"
log = "0.4"
chrono = "0.4.9"
mockall = "0.5.1"
uuid = { version = "0.7", features = ["serde", "v5"] }

[dev-dependencies]
mockall = "0.5.1"

[package.metadata.docs.rs]
all-features = false 

[[test]]
name = "integrations"
path = "../tests/integrations/mod.rs"
required-features = ["protos"]
