[package]
name = "essembly"
version = "0.1.0-alpha.1"
authors = ["blittable <blittable-bits@gmail.com>"]
edition = "2018"
description = """
Secure, performant building blocks for applications
"""
categories = ["primitives", "business", "security", "encryption"]

[features]
default = [
"core",
"app",
"cli",
"inventory",
"store",
"pos",
]

app = ["essembly-app"]
accounts = ["essembly-accounts"]
cli = ["essembly-cli"]
inventory = ["essembly-inventory"]
pos = ["essembly-pos"]
store = ["essembly-store"]
core = ["essembly-core"]

[dependencies]
essembly-app = { version = "=0.1.0-alpha.1", optional = true, path = "../essembly-app" }
essembly-cli = { version = "=0.1.0-alpha.1", optional = true, path = "../essembly-cli" }
essembly-inventory = { version = "=0.1.0-alpha.1", optional = true, path = "../essembly-inventory" }
essembly-accounts = { version = "=0.1.0-alpha.1", optional = true, path = "../essembly-accounts" }
essembly-store = { version = "=0.1.0-alpha.1", optional = true, path = "../essembly-store" }
essembly-pos = { version = "=0.1.0-alpha.1", optional = true, path = "../essembly-pos" }
essembly-core = { version = "=0.1.0-alpha.1", optional = true, path = "../essembly-core" }
tracing = "0.1.9"
bitflags = "0.1.0"
tracing-subscriber = "0.1.4"
tracing-attributes = "0.1.4"
tracing-futures = "0.0.1-alpha.1"
ansi_term = "0.12.1"
humantime = "1.3"
log = "0.4"
chrono = "0.4.9"
mockall = "0.5.1"
uuid = { version = "0.7", features = ["serde", "v5"] }

[dev-dependencies]
mockall = "0.5.1"

[package.metadata.docs.rs]
all-features = false 
