target_dir = "/tmp/target"
file_size_bytes = 5

[report_config]
output_dir = "/tmp/reports"

[[tests]]
test = "async"
target_dir = "/tmp/target"
iterations = 1

[[tests]]
test = "bsync"
target_dir = "/tmp/target"
