data_dir = "/var/lib/vector"

# Input data. Change me to a valid input source.
[sources.stdin]
  type = "stdin"
  host_key = "host"


# Output data
[sinks.out]
  inputs   = ["add_fields_transform"]
  type     = "file"
  path = "/var/lib/vector/essembly.log"
  # encoding = "text"

[transforms.add_fields_transform]
  type = "add_fields"
  inputs = ["stdin"]

  [transforms.add_fields_transform.fields]
    # A key/value pair representing the new log fields to be added. Accepts all
    # supported types. Use `.` for adding nested fields.
    # 
    # * required
    # * no default
    my_string_field = "DEBUG"
    my_env_var_field = "${ESSEMBLY_CONFIG}"
    my_timestamp_field = 1979-05-27T00:32:00Z